### ISSUE TITLE
menu_window_24bit does not seem to work on macOS

### ISSUE THREAD

**Issue by certik** [jupyter-xeus/cpp-terminal#107]
Here is how it looks like for me:

<img width="585" alt="Screen Shot 2021-03-08 at 11 28 50 AM" src="https://user-images.githubusercontent.com/20568/110364854-8c2cc900-8001-11eb-90ea-b64299e80595.png">

It's actually blinking. And when I press an arrow, it disappears.

**Comment by MCWertGaming** [comment]
Wow that's strange... we should create a stand alone demo for testing everything that cpp-terminal covers. Hve you tried it on windows yet? If it has no issue there it's probably because the macos terminal is interpreting the ANSI code wrong. We should probably really implement functions to check terminal support on runtime like ncurses can (with `colors_enabled()` or something like that but for all color options).

**Comment by certik** [comment]
We probably should. Ncurses used to detect all kinds of ancient terminals that are not in use anymore, but does not work super well in Windows. Our approach should be to support the main terminals in wide use on all platforms. We should detect what we run on and ensure we don't use features the given terminal does not support.

My initial approach with `cpp-terminal` was to strictly only support the subset which works everywhere.  That way you *know* your program will work. But I think it is also useful to support things that work almost everywhere, but then we need to be able to detect.

**Comment by flagarde** [comment]
@MCWertGaming This seems to be fixed : 

![](https://user-images.githubusercontent.com/8627746/226210457-3ef859f1-0cc9-499b-9025-2f09c1ba3e39.png)
