### ISSUE TITLE
Use clang-format

### ISSUE THREAD

**Issue by certik** [jupyter-xeus/cpp-terminal#30]
And enforce it on the CI.

**Comment by MCWertGaming** [comment]
I'm working on #76 and have looked at what options we have by using clang-format. there are some coding styles:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options
I would probably use the chromium one, I have seen that on github quiet often. What do you think? Also: Google and others don't support non c++ stuff along with their coding style, we should disable that with compile extension, just in case.
The coding styles are besically templates. You can change everything seperately, like pointers `*` left or right etc.

Also: How many spaces should 1 tab be? cpp-terminal hav either 4 or 2, depending on the file. the clang-tidy documentation uses 4 as default.

**Comment by certik** [comment]
We should use spaces and not tabs and let's use 4 spaces per indentation level.

**Comment by MCWertGaming** [comment]
Which coding style do we go with? 6 options are provided by clang-format.

**Comment by MCWertGaming** [comment]
Have added that in #91.

**Comment by MCWertGaming** [comment]
How is the state on this one? I would really like to merge #91 because the code base has so many different code styles (sometimes 2 spaces, sometimes 4 spaces, sometimes brackets in a separate line, sometimes not). What do you think about the chromium coding style? I have to fix some small things anyway (the version.h file for example).
